name: Vue Test

on:
  push:
    branches: [ main ]


jobs:
  build:
    name: TutHub-Page Test
    runs-on: ubuntu-22.04
    container:
      image: node:18
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: npm install
        run: npm install

      - name: npm build
        run: npm run build-only

      - name: rsync deployments
        uses: burnett01/rsync-deployments@5.2.1
        with:
          switches: -avzr --delete
          path: dist/
          remote_path: ${{ secrets.DEPLOY_PATH }}
          remote_host: ${{ secrets.DEPLOY_HOST }}
          remote_port: ${{ secrets.DEPLOY_PORT }}
          remote_user: ${{ secrets.DEPLOY_USER }}
          remote_key: ${{ secrets.DEPLOY_KEY }}